create table t_city (id varchar(36) not null, age integer, create_date timestamp, name varchar(30), price double, sex varchar(10), primary key (id))
create table t_coplxid1entity (id1 varchar(255) not null, id2 varchar(255) not null, name varchar(255), primary key (id1, id2))
create table t_coplxid2entity (id1 varchar(255) not null, id2 varchar(255) not null, name varchar(255), primary key (id1, id2))
create table t_city (id varchar(36) not null, age integer, create_date timestamp, name varchar(30), price double, sex varchar(10), primary key (id))
create table t_coplxid1entity (id1 varchar(255) not null, id2 varchar(255) not null, name varchar(255), primary key (id1, id2))
create table t_coplxid2entity (id1 varchar(255) not null, id2 varchar(255) not null, name varchar(255), primary key (id1, id2))
